### ISSUE TITLE
How to connect from one container to another

### ISSUE THREAD

**Issue by DerAndereAndi** [deviceplane/deviceplane#26]
Hi everyone,

thanks for developing this product. I am just trying it out locally so far it looks very interesting!

Right now I ran into an issue I can't figure out how to do this properly. As the container names are created dynamically, and the `links` property is not supported, what is currently the way to connect to a different container via 'http://containername...' ?

Thanks,
Andreas

P.S.: What is the best way to provide you feedback and ideas? Shall I write individual issues in here?

**Comment by joshwget** [comment]
We're still thinking about how we want to handle `links` and container networking in general. Links don't seem to have much of a future in Docker in any case: https://docs.docker.com/network/links/

For now we recommend using `network_mode: host` on containers. Let us know if that works for your needs!

**Comment by franklouwers** [comment]
@joshwget any plans to do docker swarm services? It's pretty lightweight, even on an underpowered platform, and solves some of these issues.

**Comment by DerAndereAndi** [comment]
@joshwget Thanks for the quick response! As I am in prototyping right now this is a good workaround. But I don't see this as a feasible setup for production. Looking forward to see what you are coming up with 😄

**Comment by joshwget** [comment]
@TheRealKern I'm pretty interested to explore why you think this isn't a good production solution. If all the containers are running on the same device, isn't this a pretty good solution?

Can you explain what you see as the limitations with this?

**Comment by DerAndereAndi** [comment]
@joshwget absolutely, I should have explained this before.

This may depend on my use-case (and maybe to my somewhat limited experience with docker yet). So let me explain the scenario first: I want to keep a set of IoT devices up to date which are not on the same network and all of them are in an actual different private network.

Right now this includes 2 different database containers and grafana in addition to a custom container with custom software.

Privacy and data security is an absolute must have. So aside from the provided interfaces on the local network (e.g. grafana), no data should be accessible from outside. So having multiple server instances run with "public" open ports is want to avoid at all costs. The services are implementation details, the custom software will provide data via an API if needed. (This is why I'd also like to have those services communicate on their own docker network)

Does this make sense?

**Comment by joshwget** [comment]
Sounds like _only_ Grafana should be accessible outside the device, and your custom software should only be able to other services running on your device.

It seems like this could still done with host networking. Grafana could bind to `0.0.0.0`, everything else could bind to `127.0.0.1`. Would that work or am I missing something more?

**Comment by DerAndereAndi** [comment]
Yeah, this is what I am trying to setup right now 👍

So me saying

> But I don't see this as a feasible setup for production.

was a bit premature it seems. Sorry for that.
