### ISSUE TITLE
Visibility into release scheduling process

### ISSUE THREAD

**Issue by AdamVig** [deviceplane/deviceplane#7]
When I deploy a release, it is unclear to me how the subsequent release scheduling process works. I typically SSH into my device and run `docker ps` repeatedly until I see that my change has taken effect.

It would be nice to have some visibility into the status of the scheduling process.

**Comment by joshwget** [comment]
Visibility into the state of services is something we definitely need more of. This is a high priority issue for us and we're going to work on it soon!

**Comment by Humancell** [comment]
Bump ... on my Device Overview, none of my running services are being displayed?

Also ... you ought to considering tightening up the page layouts ... having to scroll to the bottom of the Device Overview to see services doesn't make sense ... that is one of the most important things I want to see.

**Comment by AdamVig** [comment]
Closing this issue since this project appears to be abandoned.
