### ISSUE TITLE
Is there any available network API or plans to develop one?

### ISSUE THREAD

**Issue by logoff** [deviceplane/deviceplane#79]
Hello!

We are users of on-premises Deviceplane instance, we love it 😊.

We are used to CLI, but want to automate some things, integrated with our project modules. For that purpose is there any available network API (like REST)? We would like to have [the exact same functionality of CLI](https://deviceplane.com/docs/operating/cli/) exposed to our business logic using a network interface.

Thank you!

**Comment by joshwget** [comment]
Hey! Really glad to hear you're enjoying it.

The Deviceplane API is definitely there, just not documented well at the moment. It's REST based and fairly intuitive.

I recommend checking out the client code for the CLI (https://github.com/deviceplane/deviceplane/blob/master/pkg/client/client.go). It's not ideal, but inferring the API from that code should be possible.

Lmk if you run into any specific questions!

**Comment by logoff** [comment]
Thank you! I'll take a look.
