### ISSUE TITLE
Documentation about deploying

### ISSUE THREAD

**Issue by Gatux** [deviceplane/deviceplane#81]
Hi !

I was hopping to test deviceplan. Where can I find the documentation about "deploying" ? https://deviceplane.com/docs/deploying/ (broken link)

Thanks for the help.

**Comment by joshwget** [comment]
For now we've deprecated our Docker deployment features, but they might come back in an alternative form soon. In general, people seemed more interested in our other features rather than deployment and so we chose not to bundle deployments anymore.

**Comment by Gatux** [comment]
Ok, thanks for the reply.

**Comment by logoff** [comment]
hi @joshwget! any news about this or other features?
